Improve Ref Docs
adafruit/Adafruit_CircuitPython_MAX7219 pull request #10
Opened 2018-03-02 17:49 UTC by sommersoft

[Per Issue #566](https://github.com/adafruit/circuitpython/issues/566)

No Learn Guides found.

2018-03-04 02:18 UTC, kattni requested changes
Thanks for doing this! Please resolve the inline reviews. There are two that I don't have suggestions for, and if you can't come up with anything, leave them as they are.

2018-03-04 02:18 UTC, kattni commented on adafruit_max7219/bcddigits.py
> +        Set one digit in the display.
"Display one digit."

2018-03-04 02:18 UTC, kattni commented on adafruit_max7219/bcddigits.py
> +        Set the display from a list.
"Display digits from a list."

2018-03-04 02:18 UTC, kattni commented on adafruit_max7219/bcddigits.py
> +        Set the decimal point for a digit.
"The decimal point for a digit."

2018-03-04 02:18 UTC, kattni commented on adafruit_max7219/max7219.py
> +        Updates the display with recent changes in buffer.
"Updates the display."

2018-03-04 02:18 UTC, kattni commented on adafruit_max7219/max7219.py
> +        Sets all buffer bits to a col
This should be changed, but I'm not entirely sure what it does, so I'm not entirely sure what to set it to. If you can't think of something reasonable, then leave it.

2018-03-04 02:18 UTC, kattni commented on adafruit_max7219/max7219.py
> +        Set one buffer bit
Same as above.

2018-03-04 02:18 UTC, kattni commented on adafruit_max7219/max7219.py
> +        """Scolls the display using delta_x,delta_y."""
"Scrolls"

2018-03-05 02:28 UTC, sommersoft commented on adafruit_max7219/max7219.py
> +        Sets all buffer bits to a col
I think I know what it's doing, but haven't worked with a MAX7219 before so I can't say for sure. I made it a little more understandable, but still vague. I can put in an issue to have mrmcwethy clear up the docstring, and what it does...

2018-03-05 02:30 UTC, sommersoft commented on adafruit_max7219/max7219.py
> +        Set one buffer bit
I think I know what it's doing, but haven't worked with a MAX7219 before so I can't say for sure. I made it a little more understandable, but still vague. I can put in an issue to have mrmcwethy clear up the docstring, and what it does...

2018-03-05 04:39 UTC, kattni approved these changes

2018-03-05 04:40 UTC, kattni commented on adafruit_max7219/max7219.py
> +        Set one buffer bit
Sounds good. Thanks!

2018-03-05 04:40 UTC, kattni commented
Looks great, thanks!

2018-03-05 04:40 UTC, merged